apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoqapp-backend
  labels:
    app: hoqapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoqapp-backend
  template:
    metadata:
      labels:
        app: hoqapp-backend
    spec:
      containers:
      - name: hoqapp-backend
        image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/hoqapp-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hoqapp-backend
spec:
  type: LoadBalancer
  selector:
    app: hoqapp-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: <some-username>
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: <some-password>
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: http